### ISSUE TITLE
Login is not rendering the App

### ISSUE THREAD

**Issue by PiotrSchreiner** [PiotrSchreiner/Gmail-clone#1]
I've set up the Login Components ([Login.js](https://github.com/PiotrSchreiner/Gmail-clone/blob/main/src/Login.js), [userSlice](https://github.com/PiotrSchreiner/Gmail-clone/blob/main/src/features/userSlice.js)) and connected them to the [App.js](https://github.com/PiotrSchreiner/Gmail-clone/blob/main/src/App.js) file. However, the App is not rendering as expected. The `console.log`? indicates that it is logged in, the Redux DevTools display a payload action, and my Firebase Auth Database shows a logged-in user. This suggests that the `userSlice` and `login` functions are working correctly. However, the App is not rendering components such as the Header and Sidebar. Please help

**Comment by HaNdTriX** [comment]
Are there any Error messages inside the console or inside the terminal if yes please add/copy them to your Issue Description and use [Markdown](https://docs.github.com/de/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to show the in the right format.

## Console Errors

```
<- your errors ->
```

## Terminal Errors

```
<-- your errors -->
```

**Comment by PiotrSchreiner** [comment]
# Console Errors

<_utils.js:155 Cross-Origin-Opener-Policy policy would block the window.close call._>

# Terminal Errors

<__79 vulnerabilities 
/* All of them are mui material issues, so yes mui is a issue...but not the issue i am looking for and is causing the problems*/__>

**Comment by PiotrSchreiner** [comment]
I fixed the Issue :D
It was a typo in the userSlice reducer in userSlice.js, resolving the issue. The logout reducer now correctly updates the user state to null, ensuring proper state management. The login functionality is now working as expected. Closing the issue. #resolved #bugfix #thecodemustgoon
